name: "🚧問題回報"
labels: ["錯誤"]
projects: ["ExpTechTW/12"]
description: |
  請詳細描述你遇到的問題協助我們排除問題
body:
- type: dropdown
  id: platform
  attributes:
    label: 平台
    options:
    - iOS
    - Android
    default: 0
  validations:
    required: true
- type: textarea
  attributes:
    label: 裝置
    description: 填入裝置名稱
  validations:
    required: true
- type: textarea
  attributes:
    label: 內文
    description: 請輸入內容
  validations:
    required: true
- type: textarea
  attributes:
    label: 日誌
    description: 請輸入日誌內容
  validations:
    required: false
- type: markdown
  attributes:
    value: "### 此檔案由 ExpTech Studio 設計製作"
