name: DPIP

on:
  push:
    branches: [ "Release" ]
  pull_request:
    branches: [ "Release" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: "file"
          path: |
           build/app/outputs/flutter-apk/app-release.apk
           build/app/outputs/bundle/release/app-release.aab
